spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project1?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  profiles:
    active: dev

# 这里是配置了java的实体和数据库映射的配置文件。
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.bench.entity

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

data:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

#logging:
#  file:
#    name: D:\Code\JavaLearn\springboot-project-test\librarydemo\src\main\resources\logs\library.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %p - %m%n"
#  level:
#    web: error


